from enum import Enum
from helper import Corner
from typing import TypeAlias


class CountType(Enum):
    TRIALS = 0
    SUCCESSES = 1


class StrikingType(Enum):
    STRIKES_ATTEMPTED_BLUE = (0, 'SA', CountType.TRIALS,    Corner.BLUE)
    STRIKES_ATTEMPTED_RED  = (1, 'SA', CountType.TRIALS,    Corner.RED)
    STRIKES_LANDED_BLUE    = (2, 'SL', CountType.SUCCESSES, Corner.BLUE)
    STRIKES_LANDED_RED     = (3, 'SL', CountType.SUCCESSES, Corner.RED)

    STRIKES_FROM_STANDING_ATTEMPTED_BLUE = (4, 'SSA', CountType.TRIALS,    Corner.BLUE)
    STRIKES_FROM_STANDING_ATTEMPTED_RED  = (5, 'SSA', CountType.TRIALS,    Corner.RED)
    STRIKES_FROM_STANDING_LANDED_BLUE    = (6, 'SSL', CountType.SUCCESSES, Corner.BLUE)
    STRIKES_FROM_STANDING_LANDED_RED     = (7, 'SSL', CountType.SUCCESSES, Corner.RED)

    STRIKES_FROM_DISTANCE_ATTEMPTED_BLUE = (8,  'SDA', CountType.TRIALS,    Corner.BLUE)
    STRIKES_FROM_DISTANCE_ATTEMPTED_RED  = (9,  'SDA', CountType.TRIALS,    Corner.RED)
    STRIKES_FROM_DISTANCE_LANDED_BLUE    = (10, 'SDL', CountType.SUCCESSES, Corner.BLUE)
    STRIKES_FROM_DISTANCE_LANDED_RED     = (11, 'SDL', CountType.SUCCESSES, Corner.RED)

    STRIKES_FROM_CLINCH_ATTEMPTED_BLUE = (12, 'SCA', CountType.TRIALS,    Corner.BLUE)
    STRIKES_FROM_CLINCH_ATTEMPTED_RED  = (13, 'SCA', CountType.TRIALS,    Corner.RED)
    STRIKES_FROM_CLINCH_LANDED_BLUE    = (14, 'SCL', CountType.SUCCESSES, Corner.BLUE)
    STRIKES_FROM_CLINCH_LANDED_RED     = (15, 'SCL', CountType.SUCCESSES, Corner.RED)

    STRIKES_FROM_GROUND_ATTEMPTED_BLUE = (16, 'SGA', CountType.TRIALS,    Corner.BLUE)
    STRIKES_FROM_GROUND_ATTEMPTED_RED  = (17, 'SGA', CountType.TRIALS,    Corner.RED)
    STRIKES_FROM_GROUND_LANDED_BLUE    = (18, 'SGL', CountType.SUCCESSES, Corner.BLUE)
    STRIKES_FROM_GROUND_LANDED_RED     = (19, 'SGL', CountType.SUCCESSES, Corner.RED)

    STRIKES_AT_HEAD_ATTEMPTED_BLUE = (20, 'SHA', CountType.TRIALS,    Corner.BLUE)
    STRIKES_AT_HEAD_ATTEMPTED_RED  = (21, 'SHA', CountType.TRIALS,    Corner.RED)
    STRIKES_AT_HEAD_LANDED_BLUE    = (22, 'SHL', CountType.SUCCESSES, Corner.BLUE)
    STRIKES_AT_HEAD_LANDED_RED     = (23, 'SHL', CountType.SUCCESSES, Corner.RED)

    STRIKES_AT_BODY_ATTEMPTED_BLUE = (24, 'SBA', CountType.TRIALS,    Corner.BLUE)
    STRIKES_AT_BODY_ATTEMPTED_RED  = (25, 'SBA', CountType.TRIALS,    Corner.RED)
    STRIKES_AT_BODY_LANDED_BLUE    = (26, 'SBL', CountType.SUCCESSES, Corner.BLUE)
    STRIKES_AT_BODY_LANDED_RED     = (27, 'SBL', CountType.SUCCESSES, Corner.RED)

    STRIKES_AT_LEGS_ATTEMPTED_BLUE = (28, 'SLA', CountType.TRIALS,    Corner.BLUE)
    STRIKES_AT_LEGS_ATTEMPTED_RED  = (29, 'SLA', CountType.TRIALS,    Corner.RED)
    STRIKES_AT_LEGS_LANDED_BLUE    = (30, 'SLL', CountType.SUCCESSES, Corner.BLUE)
    STRIKES_AT_LEGS_LANDED_RED     = (31, 'SLL', CountType.SUCCESSES, Corner.RED)

    STRIKES_FROM_STANDING_AT_HEAD_ATTEMPTED_BLUE = (32, 'SSHA', CountType.TRIALS,    Corner.BLUE)
    STRIKES_FROM_STANDING_AT_HEAD_ATTEMPTED_RED  = (33, 'SSHA', CountType.TRIALS,    Corner.RED)
    STRIKES_FROM_STANDING_AT_HEAD_LANDED_BLUE    = (34, 'SSHL', CountType.SUCCESSES, Corner.BLUE)
    STRIKES_FROM_STANDING_AT_HEAD_LANDED_RED     = (35, 'SSHL', CountType.SUCCESSES, Corner.RED)

    STRIKES_FROM_STANDING_AT_BODY_ATTEMPTED_BLUE = (36, 'SSBA', CountType.TRIALS,    Corner.BLUE)
    STRIKES_FROM_STANDING_AT_BODY_ATTEMPTED_RED  = (37, 'SSBA', CountType.TRIALS,    Corner.RED)
    STRIKES_FROM_STANDING_AT_BODY_LANDED_BLUE    = (38, 'SSBL', CountType.SUCCESSES, Corner.BLUE)
    STRIKES_FROM_STANDING_AT_BODY_LANDED_RED     = (39, 'SSBL', CountType.SUCCESSES, Corner.RED)

    STRIKES_FROM_STANDING_AT_LEGS_ATTEMPTED_BLUE = (40, 'SSLA', CountType.TRIALS,    Corner.BLUE)
    STRIKES_FROM_STANDING_AT_LEGS_ATTEMPTED_RED  = (41, 'SSLA', CountType.TRIALS,    Corner.RED)
    STRIKES_FROM_STANDING_AT_LEGS_LANDED_BLUE    = (42, 'SSLL', CountType.SUCCESSES, Corner.BLUE)
    STRIKES_FROM_STANDING_AT_LEGS_LANDED_RED     = (43, 'SSLL', CountType.SUCCESSES, Corner.RED)

    STRIKES_FROM_DISTANCE_AT_HEAD_ATTEMPTED_BLUE = (44, 'SDHA', CountType.TRIALS,    Corner.BLUE)
    STRIKES_FROM_DISTANCE_AT_HEAD_ATTEMPTED_RED  = (45, 'SDHA', CountType.TRIALS,    Corner.RED)
    STRIKES_FROM_DISTANCE_AT_HEAD_LANDED_BLUE    = (46, 'SDHL', CountType.SUCCESSES, Corner.BLUE)
    STRIKES_FROM_DISTANCE_AT_HEAD_LANDED_RED     = (47, 'SDHL', CountType.SUCCESSES, Corner.RED)

    STRIKES_FROM_DISTANCE_AT_BODY_ATTEMPTED_BLUE = (48, 'SDBA', CountType.TRIALS,    Corner.BLUE)
    STRIKES_FROM_DISTANCE_AT_BODY_ATTEMPTED_RED  = (49, 'SDBA', CountType.TRIALS,    Corner.RED)
    STRIKES_FROM_DISTANCE_AT_BODY_LANDED_BLUE    = (50, 'SDBL', CountType.SUCCESSES, Corner.BLUE)
    STRIKES_FROM_DISTANCE_AT_BODY_LANDED_RED     = (51, 'SDBL', CountType.SUCCESSES, Corner.RED)

    STRIKES_FROM_DISTANCE_AT_LEGS_ATTEMPTED_BLUE = (52, 'SDLA', CountType.TRIALS,    Corner.BLUE)
    STRIKES_FROM_DISTANCE_AT_LEGS_ATTEMPTED_RED  = (53, 'SDLA', CountType.TRIALS,    Corner.RED)
    STRIKES_FROM_DISTANCE_AT_LEGS_LANDED_BLUE    = (54, 'SDLL', CountType.SUCCESSES, Corner.BLUE)
    STRIKES_FROM_DISTANCE_AT_LEGS_LANDED_RED     = (55, 'SDLL', CountType.SUCCESSES, Corner.RED)

    STRIKES_FROM_CLINCH_AT_HEAD_ATTEMPTED_BLUE = (56, 'SCHA', CountType.TRIALS,    Corner.BLUE)
    STRIKES_FROM_CLINCH_AT_HEAD_ATTEMPTED_RED  = (57, 'SCHA', CountType.TRIALS,    Corner.RED)
    STRIKES_FROM_CLINCH_AT_HEAD_LANDED_BLUE    = (58, 'SCHL', CountType.SUCCESSES, Corner.BLUE)
    STRIKES_FROM_CLINCH_AT_HEAD_LANDED_RED     = (59, 'SCHL', CountType.SUCCESSES, Corner.RED)

    STRIKES_FROM_CLINCH_AT_BODY_ATTEMPTED_BLUE = (60, 'SCBA', CountType.TRIALS,    Corner.BLUE)
    STRIKES_FROM_CLINCH_AT_BODY_ATTEMPTED_RED  = (61, 'SCBA', CountType.TRIALS,    Corner.RED)
    STRIKES_FROM_CLINCH_AT_BODY_LANDED_BLUE    = (62, 'SCBL', CountType.SUCCESSES, Corner.BLUE)
    STRIKES_FROM_CLINCH_AT_BODY_LANDED_RED     = (63, 'SCBL', CountType.SUCCESSES, Corner.RED)

    STRIKES_FROM_CLINCH_AT_LEGS_ATTEMPTED_BLUE = (64, 'SCLA', CountType.TRIALS,    Corner.BLUE)
    STRIKES_FROM_CLINCH_AT_LEGS_ATTEMPTED_RED  = (65, 'SCLA', CountType.TRIALS,    Corner.RED)
    STRIKES_FROM_CLINCH_AT_LEGS_LANDED_BLUE    = (66, 'SCLL', CountType.SUCCESSES, Corner.BLUE)
    STRIKES_FROM_CLINCH_AT_LEGS_LANDED_RED     = (67, 'SCLL', CountType.SUCCESSES, Corner.RED)

    STRIKES_FROM_GROUND_AT_HEAD_ATTEMPTED_BLUE = (68, 'SGHA', CountType.TRIALS,    Corner.BLUE)
    STRIKES_FROM_GROUND_AT_HEAD_ATTEMPTED_RED  = (69, 'SGHA', CountType.TRIALS,    Corner.RED)
    STRIKES_FROM_GROUND_AT_HEAD_LANDED_BLUE    = (70, 'SGHL', CountType.SUCCESSES, Corner.BLUE)
    STRIKES_FROM_GROUND_AT_HEAD_LANDED_RED     = (71, 'SGHL', CountType.SUCCESSES, Corner.RED)

    STRIKES_FROM_GROUND_AT_BODY_ATTEMPTED_BLUE = (72, 'SGBA', CountType.TRIALS,    Corner.BLUE)
    STRIKES_FROM_GROUND_AT_BODY_ATTEMPTED_RED  = (73, 'SGBA', CountType.TRIALS,    Corner.RED)
    STRIKES_FROM_GROUND_AT_BODY_LANDED_BLUE    = (74, 'SGBL', CountType.SUCCESSES, Corner.BLUE)
    STRIKES_FROM_GROUND_AT_BODY_LANDED_RED     = (75, 'SGBL', CountType.SUCCESSES, Corner.RED)

    STRIKES_FROM_GROUND_AT_LEGS_ATTEMPTED_BLUE = (76, 'SGLA', CountType.TRIALS,    Corner.BLUE)
    STRIKES_FROM_GROUND_AT_LEGS_ATTEMPTED_RED  = (77, 'SGLA', CountType.TRIALS,    Corner.RED)
    STRIKES_FROM_GROUND_AT_LEGS_LANDED_BLUE    = (78, 'SGLL', CountType.SUCCESSES, Corner.BLUE)
    STRIKES_FROM_GROUND_AT_LEGS_LANDED_RED     = (79, 'SGLL', CountType.SUCCESSES, Corner.RED)

    KNOCKDOWNS_LANDED_BLUE = (80, 'KDL', CountType.SUCCESSES, Corner.BLUE)
    KNOCKDOWNS_LANDED_RED  = (81, 'KDL', CountType.SUCCESSES, Corner.RED)
    KNOCKOUTS_LANDED_BLUE  = (82, 'KOL', CountType.SUCCESSES, Corner.BLUE)
    KNOCKOUTS_LANDED_RED   = (83, 'KOL', CountType.SUCCESSES, Corner.RED)

    def __init__(self, id: int, abbr: str, count_type: CountType, fighter: Corner):
        self.id = id
        self.abbr = abbr
        self.count_type = count_type
        self.fighter = fighter


class ElbowsStrikingType(Enum):
    ELBOWS_ATTEMPTED_BLUE = (0, 'EA', CountType.TRIALS,    Corner.BLUE)
    ELBOWS_ATTEMPTED_RED  = (1, 'EA', CountType.TRIALS,    Corner.RED)
    ELBOWS_LANDED_BLUE    = (2, 'EL', CountType.SUCCESSES, Corner.BLUE)
    ELBOWS_LANDED_RED     = (3, 'EL', CountType.SUCCESSES, Corner.RED)
    
    ELBOWS_FROM_STANDING_ATTEMPTED_BLUE = (4, 'ESA', CountType.TRIALS,    Corner.BLUE)
    ELBOWS_FROM_STANDING_ATTEMPTED_RED  = (5, 'ESA', CountType.TRIALS,    Corner.RED)
    ELBOWS_FROM_STANDING_LANDED_BLUE    = (6, 'ESL', CountType.SUCCESSES, Corner.BLUE)
    ELBOWS_FROM_STANDING_LANDED_RED     = (7, 'ESL', CountType.SUCCESSES, Corner.RED)
    
    ELBOWS_FROM_DISTANCE_ATTEMPTED_BLUE = (8,  'EDA', CountType.TRIALS,    Corner.BLUE)    
    ELBOWS_FROM_DISTANCE_ATTEMPTED_RED  = (9,  'EDA', CountType.TRIALS,    Corner.RED)
    ELBOWS_FROM_DISTANCE_LANDED_BLUE    = (10, 'EDL', CountType.SUCCESSES, Corner.BLUE)
    ELBOWS_FROM_DISTANCE_LANDED_RED     = (11, 'EDL', CountType.SUCCESSES, Corner.RED)
    
    ELBOWS_FROM_CLINCH_ATTEMPTED_BLUE = (12, 'ECA', CountType.TRIALS,    Corner.BLUE)
    ELBOWS_FROM_CLINCH_ATTEMPTED_RED  = (13, 'ECA', CountType.TRIALS,    Corner.RED)
    ELBOWS_FROM_CLINCH_LANDED_BLUE    = (14, 'ECL', CountType.SUCCESSES, Corner.BLUE)
    ELBOWS_FROM_CLINCH_LANDED_RED     = (15, 'ECL', CountType.SUCCESSES, Corner.RED)
    
    ELBOWS_FROM_GROUND_ATTEMPTED_BLUE = (16, 'EGA', CountType.TRIALS,    Corner.BLUE)
    ELBOWS_FROM_GROUND_ATTEMPTED_RED  = (17, 'EGA', CountType.TRIALS,    Corner.RED)
    ELBOWS_FROM_GROUND_LANDED_BLUE    = (18, 'EGL', CountType.SUCCESSES, Corner.BLUE)
    ELBOWS_FROM_GROUND_LANDED_RED     = (19, 'EGL', CountType.SUCCESSES, Corner.RED)
    
    ELBOWS_AT_HEAD_ATTEMPTED_BLUE = (20, 'EHA', CountType.TRIALS,    Corner.BLUE)
    ELBOWS_AT_HEAD_ATTEMPTED_RED  = (21, 'EHA', CountType.TRIALS,    Corner.RED)
    ELBOWS_AT_HEAD_LANDED_BLUE    = (22, 'EHL', CountType.SUCCESSES, Corner.BLUE)
    ELBOWS_AT_HEAD_LANDED_RED     = (23, 'EHL', CountType.SUCCESSES, Corner.RED)
    
    ELBOWS_AT_BODY_ATTEMPTED_BLUE = (24, 'EBA', CountType.TRIALS,    Corner.BLUE)
    ELBOWS_AT_BODY_ATTEMPTED_RED  = (25, 'EBA', CountType.TRIALS,    Corner.RED)
    ELBOWS_AT_BODY_LANDED_BLUE    = (26, 'EBL', CountType.SUCCESSES, Corner.BLUE)
    ELBOWS_AT_BODY_LANDED_RED     = (27, 'EBL', CountType.SUCCESSES, Corner.RED)
    
    ELBOWS_AT_LEGS_ATTEMPTED_BLUE = (28, 'ELA', CountType.TRIALS,    Corner.BLUE)
    ELBOWS_AT_LEGS_ATTEMPTED_RED  = (29, 'ELA', CountType.TRIALS,    Corner.RED)
    ELBOWS_AT_LEGS_LANDED_BLUE    = (30, 'ELL', CountType.SUCCESSES, Corner.BLUE)
    ELBOWS_AT_LEGS_LANDED_RED     = (31, 'ELL', CountType.SUCCESSES, Corner.RED)
    
    ELBOWS_FROM_STANDING_AT_HEAD_ATTEMPTED_BLUE = (32, 'ESHA', CountType.TRIALS,    Corner.BLUE)
    ELBOWS_FROM_STANDING_AT_HEAD_ATTEMPTED_RED  = (33, 'ESHA', CountType.TRIALS,    Corner.RED)
    ELBOWS_FROM_STANDING_AT_HEAD_LANDED_BLUE    = (34, 'ESHL', CountType.SUCCESSES, Corner.BLUE)
    ELBOWS_FROM_STANDING_AT_HEAD_LANDED_RED     = (35, 'ESHL', CountType.SUCCESSES, Corner.RED)
    
    ELBOWS_FROM_STANDING_AT_BODY_ATTEMPTED_BLUE = (36, 'ESBA', CountType.TRIALS,    Corner.BLUE)
    ELBOWS_FROM_STANDING_AT_BODY_ATTEMPTED_RED  = (37, 'ESBA', CountType.TRIALS,    Corner.RED)
    ELBOWS_FROM_STANDING_AT_BODY_LANDED_BLUE    = (38, 'ESBL', CountType.SUCCESSES, Corner.BLUE)
    ELBOWS_FROM_STANDING_AT_BODY_LANDED_RED     = (39, 'ESBL', CountType.SUCCESSES, Corner.RED)
    
    ELBOWS_FROM_STANDING_AT_LEGS_ATTEMPTED_BLUE = (40, 'ESLA', CountType.TRIALS,    Corner.BLUE)
    ELBOWS_FROM_STANDING_AT_LEGS_ATTEMPTED_RED  = (41, 'ESLA', CountType.TRIALS,    Corner.RED)
    ELBOWS_FROM_STANDING_AT_LEGS_LANDED_BLUE    = (42, 'ESLL', CountType.SUCCESSES, Corner.BLUE)
    ELBOWS_FROM_STANDING_AT_LEGS_LANDED_RED     = (43, 'ESLL', CountType.SUCCESSES, Corner.RED)
    
    ELBOWS_FROM_DISTANCE_AT_HEAD_ATTEMPTED_BLUE = (44, 'EDHA', CountType.TRIALS,    Corner.BLUE)
    ELBOWS_FROM_DISTANCE_AT_HEAD_ATTEMPTED_RED  = (45, 'EDHA', CountType.TRIALS,    Corner.RED)
    ELBOWS_FROM_DISTANCE_AT_HEAD_LANDED_BLUE    = (46, 'EDHL', CountType.SUCCESSES, Corner.BLUE)
    ELBOWS_FROM_DISTANCE_AT_HEAD_LANDED_RED     = (47, 'EDHL', CountType.SUCCESSES, Corner.RED)
    
    ELBOWS_FROM_DISTANCE_AT_BODY_ATTEMPTED_BLUE = (48, 'EDBA', CountType.TRIALS,    Corner.BLUE)
    ELBOWS_FROM_DISTANCE_AT_BODY_ATTEMPTED_RED  = (49, 'EDBA', CountType.TRIALS,    Corner.RED)
    ELBOWS_FROM_DISTANCE_AT_BODY_LANDED_BLUE    = (50, 'EDBL', CountType.SUCCESSES, Corner.BLUE)
    ELBOWS_FROM_DISTANCE_AT_BODY_LANDED_RED     = (51, 'EDBL', CountType.SUCCESSES, Corner.RED)
    
    ELBOWS_FROM_DISTANCE_AT_LEGS_ATTEMPTED_BLUE = (52, 'EDLA', CountType.TRIALS,    Corner.BLUE)
    ELBOWS_FROM_DISTANCE_AT_LEGS_ATTEMPTED_RED  = (53, 'EDLA', CountType.TRIALS,    Corner.RED)
    ELBOWS_FROM_DISTANCE_AT_LEGS_LANDED_BLUE    = (54, 'EDLL', CountType.SUCCESSES, Corner.BLUE)
    ELBOWS_FROM_DISTANCE_AT_LEGS_LANDED_RED     = (55, 'EDLL', CountType.SUCCESSES, Corner.RED)
    
    ELBOWS_FROM_CLINCH_AT_HEAD_ATTEMPTED_BLUE = (56, 'ECHA', CountType.TRIALS,    Corner.BLUE)
    ELBOWS_FROM_CLINCH_AT_HEAD_ATTEMPTED_RED  = (57, 'ECHA', CountType.TRIALS,    Corner.RED)
    ELBOWS_FROM_CLINCH_AT_HEAD_LANDED_BLUE    = (58, 'ECHL', CountType.SUCCESSES, Corner.BLUE)
    ELBOWS_FROM_CLINCH_AT_HEAD_LANDED_RED     = (59, 'ECHL', CountType.SUCCESSES, Corner.RED)
    
    ELBOWS_FROM_CLINCH_AT_BODY_ATTEMPTED_BLUE = (60, 'ECBA', CountType.TRIALS,    Corner.BLUE)
    ELBOWS_FROM_CLINCH_AT_BODY_ATTEMPTED_RED  = (61, 'ECBA', CountType.TRIALS,    Corner.RED)
    ELBOWS_FROM_CLINCH_AT_BODY_LANDED_BLUE    = (62, 'ECBL', CountType.SUCCESSES, Corner.BLUE)
    ELBOWS_FROM_CLINCH_AT_BODY_LANDED_RED     = (63, 'ECBL', CountType.SUCCESSES, Corner.RED)
    
    ELBOWS_FROM_CLINCH_AT_LEGS_ATTEMPTED_BLUE = (64, 'ECLA', CountType.TRIALS,    Corner.BLUE)
    ELBOWS_FROM_CLINCH_AT_LEGS_ATTEMPTED_RED  = (65, 'ECLA', CountType.TRIALS,    Corner.RED)
    ELBOWS_FROM_CLINCH_AT_LEGS_LANDED_BLUE    = (66, 'ECLL', CountType.SUCCESSES, Corner.BLUE)
    ELBOWS_FROM_CLINCH_AT_LEGS_LANDED_RED     = (67, 'ECLL', CountType.SUCCESSES, Corner.RED)
    
    ELBOWS_FROM_GROUND_AT_HEAD_ATTEMPTED_BLUE = (68, 'EGHA', CountType.TRIALS,    Corner.BLUE)
    ELBOWS_FROM_GROUND_AT_HEAD_ATTEMPTED_RED  = (69, 'EGHA', CountType.TRIALS,    Corner.RED)
    ELBOWS_FROM_GROUND_AT_HEAD_LANDED_BLUE    = (70, 'EGHL', CountType.SUCCESSES, Corner.BLUE)
    ELBOWS_FROM_GROUND_AT_HEAD_LANDED_RED     = (71, 'EGHL', CountType.SUCCESSES, Corner.RED)
    
    ELBOWS_FROM_GROUND_AT_BODY_ATTEMPTED_BLUE = (72, 'EGBA', CountType.TRIALS,    Corner.BLUE)
    ELBOWS_FROM_GROUND_AT_BODY_ATTEMPTED_RED  = (73, 'EGBA', CountType.TRIALS,    Corner.RED)
    ELBOWS_FROM_GROUND_AT_BODY_LANDED_BLUE    = (74, 'EGBL', CountType.SUCCESSES, Corner.BLUE)
    ELBOWS_FROM_GROUND_AT_BODY_LANDED_RED     = (75, 'EGBL', CountType.SUCCESSES, Corner.RED)
    
    ELBOWS_FROM_GROUND_AT_LEGS_ATTEMPTED_BLUE = (76, 'EGLA', CountType.TRIALS,    Corner.BLUE)
    ELBOWS_FROM_GROUND_AT_LEGS_ATTEMPTED_RED  = (77, 'EGLA', CountType.TRIALS,    Corner.RED)
    ELBOWS_FROM_GROUND_AT_LEGS_LANDED_BLUE    = (78, 'EGLL', CountType.SUCCESSES, Corner.BLUE)
    ELBOWS_FROM_GROUND_AT_LEGS_LANDED_RED     = (79, 'EGLL', CountType.SUCCESSES, Corner.RED)
    
    def __init__(self, id: int, abbr: str, count_type: CountType, fighter: Corner):
        self.id = id
        self.abbr = abbr
        self.count_type = count_type
        self.fighter = fighter


class PunchStrikingType(Enum):
    PUNCHES_ATTEMPTED_BLUE = (0, 'PA', CountType.TRIALS,    Corner.BLUE)
    PUNCHES_ATTEMPTED_RED  = (1, 'PA', CountType.TRIALS,    Corner.RED)
    PUNCHES_LANDED_BLUE    = (2, 'PL', CountType.SUCCESSES, Corner.BLUE)
    PUNCHES_LANDED_RED     = (3, 'PL', CountType.SUCCESSES, Corner.RED)

    PUNCHES_FROM_STANDING_ATTEMPTED_BLUE = (4, 'PSA', CountType.TRIALS,    Corner.BLUE)
    PUNCHES_FROM_STANDING_ATTEMPTED_RED  = (5, 'PSA', CountType.TRIALS,    Corner.RED)
    PUNCHES_FROM_STANDING_LANDED_BLUE    = (6, 'PSL', CountType.SUCCESSES, Corner.BLUE)
    PUNCHES_FROM_STANDING_LANDED_RED     = (7, 'PSL', CountType.SUCCESSES, Corner.RED)

    PUNCHES_FROM_DISTANCE_ATTEMPTED_BLUE = (8, 'PDA', CountType.TRIALS,     Corner.BLUE)
    PUNCHES_FROM_DISTANCE_ATTEMPTED_RED  = (9, 'PDA', CountType.TRIALS,     Corner.RED)
    PUNCHES_FROM_DISTANCE_LANDED_BLUE    = (10, 'PDL', CountType.SUCCESSES, Corner.BLUE)
    PUNCHES_FROM_DISTANCE_LANDED_RED     = (11, 'PDL', CountType.SUCCESSES, Corner.RED)

    PUNCHES_FROM_CLINCH_ATTEMPTED_BLUE = (12, 'PCA', CountType.TRIALS,    Corner.BLUE)
    PUNCHES_FROM_CLINCH_ATTEMPTED_RED  = (13, 'PCA', CountType.TRIALS,    Corner.RED)
    PUNCHES_FROM_CLINCH_LANDED_BLUE    = (14, 'PCL', CountType.SUCCESSES, Corner.BLUE)
    PUNCHES_FROM_CLINCH_LANDED_RED     = (15, 'PCL', CountType.SUCCESSES, Corner.RED)

    PUNCHES_FROM_GROUND_ATTEMPTED_BLUE = (16, 'PGA', CountType.TRIALS,    Corner.BLUE)
    PUNCHES_FROM_GROUND_ATTEMPTED_RED  = (17, 'PGA', CountType.TRIALS,    Corner.RED)
    PUNCHES_FROM_GROUND_LANDED_BLUE    = (18, 'PGL', CountType.SUCCESSES, Corner.BLUE)
    PUNCHES_FROM_GROUND_LANDED_RED     = (19, 'PGL', CountType.SUCCESSES, Corner.RED)

    PUNCHES_AT_HEAD_ATTEMPTED_BLUE = (20, 'PHA', CountType.TRIALS,    Corner.BLUE)
    PUNCHES_AT_HEAD_ATTEMPTED_RED  = (21, 'PHA', CountType.TRIALS,    Corner.RED)
    PUNCHES_AT_HEAD_LANDED_BLUE    = (22, 'PHL', CountType.SUCCESSES, Corner.BLUE)
    PUNCHES_AT_HEAD_LANDED_RED     = (23, 'PHL', CountType.SUCCESSES, Corner.RED)

    PUNCHES_AT_BODY_ATTEMPTED_BLUE = (24, 'PBA', CountType.TRIALS,    Corner.BLUE)
    PUNCHES_AT_BODY_ATTEMPTED_RED  = (25, 'PBA', CountType.TRIALS,    Corner.RED)
    PUNCHES_AT_BODY_LANDED_BLUE    = (26, 'PBL', CountType.SUCCESSES, Corner.BLUE)
    PUNCHES_AT_BODY_LANDED_RED     = (27, 'PBL', CountType.SUCCESSES, Corner.RED)

    PUNCHES_AT_LEGS_ATTEMPTED_BLUE = (28, 'PLA', CountType.TRIALS,    Corner.BLUE)
    PUNCHES_AT_LEGS_ATTEMPTED_RED  = (29, 'PLA', CountType.TRIALS,    Corner.RED)
    PUNCHES_AT_LEGS_LANDED_BLUE    = (30, 'PLL', CountType.SUCCESSES, Corner.BLUE)
    PUNCHES_AT_LEGS_LANDED_RED     = (31, 'PLL', CountType.SUCCESSES, Corner.RED)

    PUNCHES_FROM_STANDING_AT_HEAD_ATTEMPTED_BLUE = (32, 'PSHA', CountType.TRIALS,    Corner.BLUE)
    PUNCHES_FROM_STANDING_AT_HEAD_ATTEMPTED_RED  = (33, 'PSHA', CountType.TRIALS,    Corner.RED)
    PUNCHES_FROM_STANDING_AT_HEAD_LANDED_BLUE    = (34, 'PSHL', CountType.SUCCESSES, Corner.BLUE)
    PUNCHES_FROM_STANDING_AT_HEAD_LANDED_RED     = (35, 'PSHL', CountType.SUCCESSES, Corner.RED)

    PUNCHES_FROM_STANDING_AT_BODY_ATTEMPTED_BLUE = (36, 'PSBA', CountType.TRIALS,     Corner.BLUE)
    PUNCHES_FROM_STANDING_AT_BODY_ATTEMPTED_RED  = (37, 'PSBA', CountType.TRIALS,     Corner.RED)
    PUNCHES_FROM_STANDING_AT_BODY_LANDED_BLUE    = (38, 'PSBL', CountType.SUCCESSES,  Corner.BLUE)
    PUNCHES_FROM_STANDING_AT_BODY_LANDED_RED     = (39, 'PSBL', CountType.SUCCESSES,  Corner.RED)

    PUNCHES_FROM_STANDING_AT_LEGS_ATTEMPTED_BLUE = (40, 'PSLA', CountType.TRIALS,    Corner.BLUE)
    PUNCHES_FROM_STANDING_AT_LEGS_ATTEMPTED_RED  = (41, 'PSLA', CountType.TRIALS,    Corner.RED)
    PUNCHES_FROM_STANDING_AT_LEGS_LANDED_BLUE    = (42, 'PSLL', CountType.SUCCESSES, Corner.BLUE)
    PUNCHES_FROM_STANDING_AT_LEGS_LANDED_RED     = (43, 'PSLL', CountType.SUCCESSES, Corner.RED)

    PUNCHES_FROM_DISTANCE_AT_HEAD_ATTEMPTED_BLUE = (44, 'PDHA', CountType.TRIALS,    Corner.BLUE)
    PUNCHES_FROM_DISTANCE_AT_HEAD_ATTEMPTED_RED  = (45, 'PDHA', CountType.TRIALS,    Corner.RED)
    PUNCHES_FROM_DISTANCE_AT_HEAD_LANDED_BLUE    = (46, 'PDHL', CountType.SUCCESSES, Corner.BLUE)
    PUNCHES_FROM_DISTANCE_AT_HEAD_LANDED_RED     = (47, 'PDHL', CountType.SUCCESSES, Corner.RED)

    PUNCHES_FROM_DISTANCE_AT_BODY_ATTEMPTED_BLUE = (48, 'PDBA', CountType.TRIALS,    Corner.BLUE)
    PUNCHES_FROM_DISTANCE_AT_BODY_ATTEMPTED_RED  = (49, 'PDBA', CountType.TRIALS,    Corner.RED)
    PUNCHES_FROM_DISTANCE_AT_BODY_LANDED_BLUE    = (50, 'PDBL', CountType.SUCCESSES, Corner.BLUE)
    PUNCHES_FROM_DISTANCE_AT_BODY_LANDED_RED     = (51, 'PDBL', CountType.SUCCESSES, Corner.RED)

    PUNCHES_FROM_DISTANCE_AT_LEGS_ATTEMPTED_BLUE = (52, 'PDLA', CountType.TRIALS,    Corner.BLUE)
    PUNCHES_FROM_DISTANCE_AT_LEGS_ATTEMPTED_RED  = (53, 'PDLA', CountType.TRIALS,    Corner.RED)
    PUNCHES_FROM_DISTANCE_AT_LEGS_LANDED_BLUE    = (54, 'PDLL', CountType.SUCCESSES, Corner.BLUE)
    PUNCHES_FROM_DISTANCE_AT_LEGS_LANDED_RED     = (55, 'PDLL', CountType.SUCCESSES, Corner.RED)

    PUNCHES_FROM_CLINCH_AT_HEAD_ATTEMPTED_BLUE = (56, 'PCHA', CountType.TRIALS,    Corner.BLUE)
    PUNCHES_FROM_CLINCH_AT_HEAD_ATTEMPTED_RED  = (57, 'PCHA', CountType.TRIALS,    Corner.RED)
    PUNCHES_FROM_CLINCH_AT_HEAD_LANDED_BLUE    = (58, 'PCHL', CountType.SUCCESSES, Corner.BLUE)
    PUNCHES_FROM_CLINCH_AT_HEAD_LANDED_RED     = (59, 'PCHL', CountType.SUCCESSES, Corner.RED)

    PUNCHES_FROM_CLINCH_AT_BODY_ATTEMPTED_BLUE = (60, 'PCBA', CountType.TRIALS,    Corner.BLUE)
    PUNCHES_FROM_CLINCH_AT_BODY_ATTEMPTED_RED  = (61, 'PCBA', CountType.TRIALS,    Corner.RED)
    PUNCHES_FROM_CLINCH_AT_BODY_LANDED_BLUE    = (62, 'PCBL', CountType.SUCCESSES, Corner.BLUE)
    PUNCHES_FROM_CLINCH_AT_BODY_LANDED_RED     = (63, 'PCBL', CountType.SUCCESSES, Corner.RED)

    PUNCHES_FROM_CLINCH_AT_LEGS_ATTEMPTED_BLUE = (64, 'PCLA', CountType.TRIALS,    Corner.BLUE)
    PUNCHES_FROM_CLINCH_AT_LEGS_ATTEMPTED_RED  = (65, 'PCLA', CountType.TRIALS,    Corner.RED)
    PUNCHES_FROM_CLINCH_AT_LEGS_LANDED_BLUE    = (66, 'PCLL', CountType.SUCCESSES, Corner.BLUE)
    PUNCHES_FROM_CLINCH_AT_LEGS_LANDED_RED     = (67, 'PCLL', CountType.SUCCESSES, Corner.RED)

    PUNCHES_FROM_GROUND_AT_HEAD_ATTEMPTED_BLUE = (68, 'PGHA', CountType.TRIALS,    Corner.BLUE)
    PUNCHES_FROM_GROUND_AT_HEAD_ATTEMPTED_RED  = (69, 'PGHA', CountType.TRIALS,    Corner.RED)
    PUNCHES_FROM_GROUND_AT_HEAD_LANDED_BLUE    = (70, 'PGHL', CountType.SUCCESSES, Corner.BLUE)
    PUNCHES_FROM_GROUND_AT_HEAD_LANDED_RED     = (71, 'PGHL', CountType.SUCCESSES, Corner.RED)

    PUNCHES_FROM_GROUND_AT_BODY_ATTEMPTED_BLUE = (72, 'PGBA', CountType.TRIALS,    Corner.BLUE)
    PUNCHES_FROM_GROUND_AT_BODY_ATTEMPTED_RED  = (73, 'PGBA', CountType.TRIALS,    Corner.RED)
    PUNCHES_FROM_GROUND_AT_BODY_LANDED_BLUE    = (74, 'PGBL', CountType.SUCCESSES, Corner.BLUE)
    PUNCHES_FROM_GROUND_AT_BODY_LANDED_RED     = (75, 'PGBL', CountType.SUCCESSES, Corner.RED)

    PUNCHES_FROM_GROUND_AT_LEGS_ATTEMPTED_BLUE = (76, 'PGLA', CountType.TRIALS,    Corner.BLUE)
    PUNCHES_FROM_GROUND_AT_LEGS_ATTEMPTED_RED  = (77, 'PGLA', CountType.TRIALS,    Corner.RED)
    PUNCHES_FROM_GROUND_AT_LEGS_LANDED_BLUE    = (78, 'PGLL', CountType.SUCCESSES, Corner.BLUE)
    PUNCHES_FROM_GROUND_AT_LEGS_LANDED_RED     = (79, 'PGLL', CountType.SUCCESSES, Corner.RED)

    def __init__(self, id: int, abbr: str, count_type: CountType, fighter: Corner):
        self.id = id
        self.abbr = abbr
        self.count_type = count_type
        self.fighter = fighter


class KneeStrikingType(Enum):
    KNEES_ATTEMPTED_BLUE = (0, 'KNA', CountType.TRIALS,    Corner.BLUE)
    KNEES_ATTEMPTED_RED  = (1, 'KNA', CountType.TRIALS,    Corner.RED)
    KNEES_LANDED_BLUE    = (2, 'KNL', CountType.SUCCESSES, Corner.BLUE)
    KNEES_LANDED_RED     = (3, 'KNL', CountType.SUCCESSES, Corner.RED)

    KNEES_FROM_STANDING_ATTEMPTED_BLUE = (4, 'KNSA', CountType.TRIALS,    Corner.BLUE)
    KNEES_FROM_STANDING_ATTEMPTED_RED  = (5, 'KNSA', CountType.TRIALS,    Corner.RED)
    KNEES_FROM_STANDING_LANDED_BLUE    = (6, 'KNSL', CountType.SUCCESSES, Corner.BLUE)
    KNEES_FROM_STANDING_LANDED_RED     = (7, 'KNSL', CountType.SUCCESSES, Corner.RED)

    KNEES_FROM_DISTANCE_ATTEMPTED_BLUE = (8, 'KNDA', CountType.TRIALS,     Corner.BLUE)
    KNEES_FROM_DISTANCE_ATTEMPTED_RED  = (9, 'KNDA', CountType.TRIALS,     Corner.RED)
    KNEES_FROM_DISTANCE_LANDED_BLUE    = (10, 'KNDL', CountType.SUCCESSES, Corner.BLUE)
    KNEES_FROM_DISTANCE_LANDED_RED     = (11, 'KNDL', CountType.SUCCESSES, Corner.RED)

    KNEES_FROM_CLINCH_ATTEMPTED_BLUE = (12, 'KNCA', CountType.TRIALS,    Corner.BLUE)
    KNEES_FROM_CLINCH_ATTEMPTED_RED  = (13, 'KNCA', CountType.TRIALS,    Corner.RED)
    KNEES_FROM_CLINCH_LANDED_BLUE    = (14, 'KNCL', CountType.SUCCESSES, Corner.BLUE)
    KNEES_FROM_CLINCH_LANDED_RED     = (15, 'KNCL', CountType.SUCCESSES, Corner.RED)

    KNEES_FROM_GROUND_ATTEMPTED_BLUE = (16, 'KNGA', CountType.TRIALS,    Corner.BLUE)
    KNEES_FROM_GROUND_ATTEMPTED_RED  = (17, 'KNGA', CountType.TRIALS,    Corner.RED)
    KNEES_FROM_GROUND_LANDED_BLUE    = (18, 'KNGL', CountType.SUCCESSES, Corner.BLUE)
    KNEES_FROM_GROUND_LANDED_RED     = (19, 'KNGL', CountType.SUCCESSES, Corner.RED)

    KNEES_AT_HEAD_ATTEMPTED_BLUE = (20, 'KNHA', CountType.TRIALS,    Corner.BLUE)
    KNEES_AT_HEAD_ATTEMPTED_RED  = (21, 'KNHA', CountType.TRIALS,    Corner.RED)
    KNEES_AT_HEAD_LANDED_BLUE    = (22, 'KNHL', CountType.SUCCESSES, Corner.BLUE)
    KNEES_AT_HEAD_LANDED_RED     = (23, 'KNHL', CountType.SUCCESSES, Corner.RED)

    KNEES_AT_BODY_ATTEMPTED_BLUE = (24, 'KNBA', CountType.TRIALS,    Corner.BLUE)
    KNEES_AT_BODY_ATTEMPTED_RED  = (25, 'KNBA', CountType.TRIALS,    Corner.RED)
    KNEES_AT_BODY_LANDED_BLUE    = (26, 'KNBL', CountType.SUCCESSES, Corner.BLUE)
    KNEES_AT_BODY_LANDED_RED     = (27, 'KNBL', CountType.SUCCESSES, Corner.RED)

    KNEES_AT_LEGS_ATTEMPTED_BLUE = (28, 'KNLA', CountType.TRIALS,    Corner.BLUE)
    KNEES_AT_LEGS_ATTEMPTED_RED  = (29, 'KNLA', CountType.TRIALS,    Corner.RED)
    KNEES_AT_LEGS_LANDED_BLUE    = (30, 'KNLL', CountType.SUCCESSES, Corner.BLUE)
    KNEES_AT_LEGS_LANDED_RED     = (31, 'KNLL', CountType.SUCCESSES, Corner.RED)

    KNEES_FROM_STANDING_AT_HEAD_ATTEMPTED_BLUE = (32, 'KNSHA', CountType.TRIALS,    Corner.BLUE)
    KNEES_FROM_STANDING_AT_HEAD_ATTEMPTED_RED  = (33, 'KNSHA', CountType.TRIALS,    Corner.RED)
    KNEES_FROM_STANDING_AT_HEAD_LANDED_BLUE    = (34, 'KNSHL', CountType.SUCCESSES, Corner.BLUE)
    KNEES_FROM_STANDING_AT_HEAD_LANDED_RED     = (35, 'KNSHL', CountType.SUCCESSES, Corner.RED)

    KNEES_FROM_STANDING_AT_BODY_ATTEMPTED_BLUE = (36, 'KNSBA', CountType.TRIALS,    Corner.BLUE)
    KNEES_FROM_STANDING_AT_BODY_ATTEMPTED_RED  = (37, 'KNSBA', CountType.TRIALS,    Corner.RED)
    KNEES_FROM_STANDING_AT_BODY_LANDED_BLUE    = (38, 'KNSBL', CountType.SUCCESSES, Corner.BLUE)
    KNEES_FROM_STANDING_AT_BODY_LANDED_RED     = (39, 'KNSBL', CountType.SUCCESSES, Corner.RED)

    KNEES_FROM_STANDING_AT_LEGS_ATTEMPTED_BLUE = (40, 'KNSLA', CountType.TRIALS,    Corner.BLUE)
    KNEES_FROM_STANDING_AT_LEGS_ATTEMPTED_RED  = (41, 'KNSLA', CountType.TRIALS,    Corner.RED)
    KNEES_FROM_STANDING_AT_LEGS_LANDED_BLUE    = (42, 'KNSLL', CountType.SUCCESSES, Corner.BLUE)
    KNEES_FROM_STANDING_AT_LEGS_LANDED_RED     = (43, 'KNSLL', CountType.SUCCESSES, Corner.RED)

    KNEES_FROM_DISTANCE_AT_HEAD_ATTEMPTED_BLUE = (44, 'KNDHA', CountType.TRIALS,    Corner.BLUE)
    KNEES_FROM_DISTANCE_AT_HEAD_ATTEMPTED_RED  = (45, 'KNDHA', CountType.TRIALS,    Corner.RED)
    KNEES_FROM_DISTANCE_AT_HEAD_LANDED_BLUE    = (46, 'KNDHL', CountType.SUCCESSES, Corner.BLUE)
    KNEES_FROM_DISTANCE_AT_HEAD_LANDED_RED     = (47, 'KNDHL', CountType.SUCCESSES, Corner.RED)

    KNEES_FROM_DISTANCE_AT_BODY_ATTEMPTED_BLUE = (48, 'KNDBA', CountType.TRIALS,    Corner.BLUE)
    KNEES_FROM_DISTANCE_AT_BODY_ATTEMPTED_RED  = (49, 'KNDBA', CountType.TRIALS,    Corner.RED)
    KNEES_FROM_DISTANCE_AT_BODY_LANDED_BLUE    = (50, 'KNDBL', CountType.SUCCESSES, Corner.BLUE)
    KNEES_FROM_DISTANCE_AT_BODY_LANDED_RED     = (51, 'KNDBL', CountType.SUCCESSES, Corner.RED)

    KNEES_FROM_DISTANCE_AT_LEGS_ATTEMPTED_BLUE = (52, 'KNDLA', CountType.TRIALS,    Corner.BLUE)
    KNEES_FROM_DISTANCE_AT_LEGS_ATTEMPTED_RED  = (53, 'KNDLA', CountType.TRIALS,    Corner.RED)
    KNEES_FROM_DISTANCE_AT_LEGS_LANDED_BLUE    = (54, 'KNDLL', CountType.SUCCESSES, Corner.BLUE)
    KNEES_FROM_DISTANCE_AT_LEGS_LANDED_RED     = (55, 'KNDLL', CountType.SUCCESSES, Corner.RED)

    KNEES_FROM_CLINCH_AT_HEAD_ATTEMPTED_BLUE = (56, 'KNCHA', CountType.TRIALS,    Corner.BLUE)
    KNEES_FROM_CLINCH_AT_HEAD_ATTEMPTED_RED  = (57, 'KNCHA', CountType.TRIALS,    Corner.RED)
    KNEES_FROM_CLINCH_AT_HEAD_LANDED_BLUE    = (58, 'KNCHL', CountType.SUCCESSES, Corner.BLUE)
    KNEES_FROM_CLINCH_AT_HEAD_LANDED_RED     = (59, 'KNCHL', CountType.SUCCESSES, Corner.RED)

    KNEES_FROM_CLINCH_AT_BODY_ATTEMPTED_BLUE = (60, 'KNCBA', CountType.TRIALS,    Corner.BLUE)
    KNEES_FROM_CLINCH_AT_BODY_ATTEMPTED_RED  = (61, 'KNCBA', CountType.TRIALS,    Corner.RED)
    KNEES_FROM_CLINCH_AT_BODY_LANDED_BLUE    = (62, 'KNCBL', CountType.SUCCESSES, Corner.BLUE)
    KNEES_FROM_CLINCH_AT_BODY_LANDED_RED     = (63, 'KNCBL', CountType.SUCCESSES, Corner.RED)

    KNEES_FROM_CLINCH_AT_LEGS_ATTEMPTED_BLUE = (64, 'KNCLA', CountType.TRIALS,    Corner.BLUE)
    KNEES_FROM_CLINCH_AT_LEGS_ATTEMPTED_RED  = (65, 'KNCLA', CountType.TRIALS,    Corner.RED)
    KNEES_FROM_CLINCH_AT_LEGS_LANDED_BLUE    = (66, 'KNCLL', CountType.SUCCESSES, Corner.BLUE)
    KNEES_FROM_CLINCH_AT_LEGS_LANDED_RED     = (67, 'KNCLL', CountType.SUCCESSES, Corner.RED)

    KNEES_FROM_GROUND_AT_HEAD_ATTEMPTED_BLUE = (68, 'KNGHA', CountType.TRIALS,    Corner.BLUE)
    KNEES_FROM_GROUND_AT_HEAD_ATTEMPTED_RED  = (69, 'KNGHA', CountType.TRIALS,    Corner.RED)
    KNEES_FROM_GROUND_AT_HEAD_LANDED_BLUE    = (70, 'KNGHL', CountType.SUCCESSES, Corner.BLUE)
    KNEES_FROM_GROUND_AT_HEAD_LANDED_RED     = (71, 'KNGHL', CountType.SUCCESSES, Corner.RED)

    KNEES_FROM_GROUND_AT_BODY_ATTEMPTED_BLUE = (72, 'KNGBA', CountType.TRIALS,    Corner.BLUE)
    KNEES_FROM_GROUND_AT_BODY_ATTEMPTED_RED  = (73, 'KNGBA', CountType.TRIALS,    Corner.RED)
    KNEES_FROM_GROUND_AT_BODY_LANDED_BLUE    = (74, 'KNGBL', CountType.SUCCESSES, Corner.BLUE)
    KNEES_FROM_GROUND_AT_BODY_LANDED_RED     = (75, 'KNGBL', CountType.SUCCESSES, Corner.RED)

    KNEES_FROM_GROUND_AT_LEGS_ATTEMPTED_BLUE = (76, 'KNGLA', CountType.TRIALS,    Corner.BLUE)
    KNEES_FROM_GROUND_AT_LEGS_ATTEMPTED_RED  = (77, 'KNGLA', CountType.TRIALS,    Corner.RED)
    KNEES_FROM_GROUND_AT_LEGS_LANDED_BLUE    = (78, 'KNGLL', CountType.SUCCESSES, Corner.BLUE)
    KNEES_FROM_GROUND_AT_LEGS_LANDED_RED     = (79, 'KNGLL', CountType.SUCCESSES, Corner.RED)

    def __init__(self, id: int, abbr: str, count_type: CountType, fighter: Corner):
        self.id = id
        self.abbr = abbr
        self.count_type = count_type
        self.fighter = fighter



class KickStrikingType(Enum):
    KICKS_ATTEMPTED_BLUE = (0, 'KIA', CountType.TRIALS,    Corner.BLUE)
    KICKS_ATTEMPTED_RED  = (1, 'KIA', CountType.TRIALS,    Corner.RED)
    KICKS_LANDED_BLUE    = (2, 'KIL', CountType.SUCCESSES, Corner.BLUE)
    KICKS_LANDED_RED     = (3, 'KIL', CountType.SUCCESSES, Corner.RED)

    KICKS_FROM_STANDING_ATTEMPTED_BLUE = (4, 'KISA', CountType.TRIALS,    Corner.BLUE)
    KICKS_FROM_STANDING_ATTEMPTED_RED  = (5, 'KISA', CountType.TRIALS,    Corner.RED)
    KICKS_FROM_STANDING_LANDED_BLUE    = (6, 'KISL', CountType.SUCCESSES, Corner.BLUE)
    KICKS_FROM_STANDING_LANDED_RED     = (7, 'KISL', CountType.SUCCESSES, Corner.RED)

    KICKS_FROM_DISTANCE_ATTEMPTED_BLUE = (8, 'KIDA', CountType.TRIALS,     Corner.BLUE)
    KICKS_FROM_DISTANCE_ATTEMPTED_RED  = (9, 'KIDA', CountType.TRIALS,     Corner.RED)
    KICKS_FROM_DISTANCE_LANDED_BLUE    = (10, 'KIDL', CountType.SUCCESSES, Corner.BLUE)
    KICKS_FROM_DISTANCE_LANDED_RED     = (11, 'KIDL', CountType.SUCCESSES, Corner.RED)

    KICKS_FROM_CLINCH_ATTEMPTED_BLUE = (12, 'KICA', CountType.TRIALS,    Corner.BLUE)
    KICKS_FROM_CLINCH_ATTEMPTED_RED  = (13, 'KICA', CountType.TRIALS,    Corner.RED)
    KICKS_FROM_CLINCH_LANDED_BLUE    = (14, 'KICL', CountType.SUCCESSES, Corner.BLUE)
    KICKS_FROM_CLINCH_LANDED_RED     = (15, 'KICL', CountType.SUCCESSES, Corner.RED)

    KICKS_FROM_GROUND_ATTEMPTED_BLUE = (16, 'KIGA', CountType.TRIALS,    Corner.BLUE)
    KICKS_FROM_GROUND_ATTEMPTED_RED  = (17, 'KIGA', CountType.TRIALS,    Corner.RED)
    KICKS_FROM_GROUND_LANDED_BLUE    = (18, 'KIGL', CountType.SUCCESSES, Corner.BLUE)
    KICKS_FROM_GROUND_LANDED_RED     = (19, 'KIGL', CountType.SUCCESSES, Corner.RED)

    KICKS_AT_HEAD_ATTEMPTED_BLUE = (20, 'KIHA', CountType.TRIALS,    Corner.BLUE)
    KICKS_AT_HEAD_ATTEMPTED_RED  = (21, 'KIHA', CountType.TRIALS,    Corner.RED)
    KICKS_AT_HEAD_LANDED_BLUE    = (22, 'KIHL', CountType.SUCCESSES, Corner.BLUE)
    KICKS_AT_HEAD_LANDED_RED     = (23, 'KIHL', CountType.SUCCESSES, Corner.RED)

    KICKS_AT_BODY_ATTEMPTED_BLUE = (24, 'KIBA', CountType.TRIALS,    Corner.BLUE)
    KICKS_AT_BODY_ATTEMPTED_RED  = (25, 'KIBA', CountType.TRIALS,    Corner.RED)
    KICKS_AT_BODY_LANDED_BLUE    = (26, 'KIBL', CountType.SUCCESSES, Corner.BLUE)
    KICKS_AT_BODY_LANDED_RED     = (27, 'KIBL', CountType.SUCCESSES, Corner.RED)

    KICKS_AT_LEGS_ATTEMPTED_BLUE = (28, 'KILA', CountType.TRIALS,    Corner.BLUE)
    KICKS_AT_LEGS_ATTEMPTED_RED  = (29, 'KILA', CountType.TRIALS,    Corner.RED)
    KICKS_AT_LEGS_LANDED_BLUE    = (30, 'KILL', CountType.SUCCESSES, Corner.BLUE)
    KICKS_AT_LEGS_LANDED_RED     = (31, 'KILL', CountType.SUCCESSES, Corner.RED)

    KICKS_FROM_STANDING_AT_HEAD_ATTEMPTED_BLUE = (32, 'KISHA', CountType.TRIALS,    Corner.BLUE)
    KICKS_FROM_STANDING_AT_HEAD_ATTEMPTED_RED  = (33, 'KISHA', CountType.TRIALS,    Corner.RED)
    KICKS_FROM_STANDING_AT_HEAD_LANDED_BLUE    = (34, 'KISHL', CountType.SUCCESSES, Corner.BLUE)
    KICKS_FROM_STANDING_AT_HEAD_LANDED_RED     = (35, 'KISHL', CountType.SUCCESSES, Corner.RED)

    KICKS_FROM_STANDING_AT_BODY_ATTEMPTED_BLUE = (36, 'KISBA', CountType.TRIALS,    Corner.BLUE)
    KICKS_FROM_STANDING_AT_BODY_ATTEMPTED_RED  = (37, 'KISBA', CountType.TRIALS,    Corner.RED)
    KICKS_FROM_STANDING_AT_BODY_LANDED_BLUE    = (38, 'KISBL', CountType.SUCCESSES, Corner.BLUE)
    KICKS_FROM_STANDING_AT_BODY_LANDED_RED     = (39, 'KISBL', CountType.SUCCESSES, Corner.RED)

    KICKS_FROM_STANDING_AT_LEGS_ATTEMPTED_BLUE = (40, 'KISLA', CountType.TRIALS,    Corner.BLUE)
    KICKS_FROM_STANDING_AT_LEGS_ATTEMPTED_RED  = (41, 'KISLA', CountType.TRIALS,    Corner.RED)
    KICKS_FROM_STANDING_AT_LEGS_LANDED_BLUE    = (42, 'KISLL', CountType.SUCCESSES, Corner.BLUE)
    KICKS_FROM_STANDING_AT_LEGS_LANDED_RED     = (43, 'KISLL', CountType.SUCCESSES, Corner.RED)

    KICKS_FROM_DISTANCE_AT_HEAD_ATTEMPTED_BLUE = (44, 'KIDHA', CountType.TRIALS,    Corner.BLUE)
    KICKS_FROM_DISTANCE_AT_HEAD_ATTEMPTED_RED  = (45, 'KIDHA', CountType.TRIALS,    Corner.RED)
    KICKS_FROM_DISTANCE_AT_HEAD_LANDED_BLUE    = (46, 'KIDHL', CountType.SUCCESSES, Corner.BLUE)
    KICKS_FROM_DISTANCE_AT_HEAD_LANDED_RED     = (47, 'KIDHL', CountType.SUCCESSES, Corner.RED)

    KICKS_FROM_DISTANCE_AT_BODY_ATTEMPTED_BLUE = (48, 'KIDBA', CountType.TRIALS,    Corner.BLUE)
    KICKS_FROM_DISTANCE_AT_BODY_ATTEMPTED_RED  = (49, 'KIDBA', CountType.TRIALS,    Corner.RED)
    KICKS_FROM_DISTANCE_AT_BODY_LANDED_BLUE    = (50, 'KIDBL', CountType.SUCCESSES, Corner.BLUE)
    KICKS_FROM_DISTANCE_AT_BODY_LANDED_RED     = (51, 'KIDBL', CountType.SUCCESSES, Corner.RED)

    KICKS_FROM_DISTANCE_AT_LEGS_ATTEMPTED_BLUE = (52, 'KIDLA', CountType.TRIALS,    Corner.BLUE)
    KICKS_FROM_DISTANCE_AT_LEGS_ATTEMPTED_RED  = (53, 'KIDLA', CountType.TRIALS,    Corner.RED)
    KICKS_FROM_DISTANCE_AT_LEGS_LANDED_BLUE    = (54, 'KIDLL', CountType.SUCCESSES, Corner.BLUE)
    KICKS_FROM_DISTANCE_AT_LEGS_LANDED_RED     = (55, 'KIDLL', CountType.SUCCESSES, Corner.RED)

    KICKS_FROM_CLINCH_AT_HEAD_ATTEMPTED_BLUE = (56, 'KICHA', CountType.TRIALS,    Corner.BLUE)
    KICKS_FROM_CLINCH_AT_HEAD_ATTEMPTED_RED  = (57, 'KICHA', CountType.TRIALS,    Corner.RED)
    KICKS_FROM_CLINCH_AT_HEAD_LANDED_BLUE    = (58, 'KICHL', CountType.SUCCESSES, Corner.BLUE)
    KICKS_FROM_CLINCH_AT_HEAD_LANDED_RED     = (59, 'KICHL', CountType.SUCCESSES, Corner.RED)

    KICKS_FROM_CLINCH_AT_BODY_ATTEMPTED_BLUE = (60, 'KICBA', CountType.TRIALS,    Corner.BLUE)
    KICKS_FROM_CLINCH_AT_BODY_ATTEMPTED_RED  = (61, 'KICBA', CountType.TRIALS,    Corner.RED)
    KICKS_FROM_CLINCH_AT_BODY_LANDED_BLUE    = (62, 'KICBL', CountType.SUCCESSES, Corner.BLUE)
    KICKS_FROM_CLINCH_AT_BODY_LANDED_RED     = (63, 'KICBL', CountType.SUCCESSES, Corner.RED)

    KICKS_FROM_CLINCH_AT_LEGS_ATTEMPTED_BLUE = (64, 'KICLA', CountType.TRIALS,    Corner.BLUE)
    KICKS_FROM_CLINCH_AT_LEGS_ATTEMPTED_RED  = (65, 'KICLA', CountType.TRIALS,    Corner.RED)
    KICKS_FROM_CLINCH_AT_LEGS_LANDED_BLUE    = (66, 'KICLL', CountType.SUCCESSES, Corner.BLUE)
    KICKS_FROM_CLINCH_AT_LEGS_LANDED_RED     = (67, 'KICLL', CountType.SUCCESSES, Corner.RED)

    KICKS_FROM_GROUND_AT_HEAD_ATTEMPTED_BLUE = (68, 'KIGHA', CountType.TRIALS,    Corner.BLUE)
    KICKS_FROM_GROUND_AT_HEAD_ATTEMPTED_RED  = (69, 'KIGHA', CountType.TRIALS,    Corner.RED)
    KICKS_FROM_GROUND_AT_HEAD_LANDED_BLUE    = (70, 'KIGHL', CountType.SUCCESSES, Corner.BLUE)
    KICKS_FROM_GROUND_AT_HEAD_LANDED_RED     = (71, 'KIGHL', CountType.SUCCESSES, Corner.RED)

    KICKS_FROM_GROUND_AT_BODY_ATTEMPTED_BLUE = (72, 'KIGBA', CountType.TRIALS,    Corner.BLUE)
    KICKS_FROM_GROUND_AT_BODY_ATTEMPTED_RED  = (73, 'KIGBA', CountType.TRIALS,    Corner.RED)
    KICKS_FROM_GROUND_AT_BODY_LANDED_BLUE    = (74, 'KIGBL', CountType.SUCCESSES, Corner.BLUE)
    KICKS_FROM_GROUND_AT_BODY_LANDED_RED     = (75, 'KIGBL', CountType.SUCCESSES, Corner.RED)

    KICKS_FROM_GROUND_AT_LEGS_ATTEMPTED_BLUE = (76, 'KIGLA', CountType.TRIALS,    Corner.BLUE)
    KICKS_FROM_GROUND_AT_LEGS_ATTEMPTED_RED  = (77, 'KIGLA', CountType.TRIALS,    Corner.RED)
    KICKS_FROM_GROUND_AT_LEGS_LANDED_BLUE    = (78, 'KIGLL', CountType.SUCCESSES, Corner.BLUE)
    KICKS_FROM_GROUND_AT_LEGS_LANDED_RED     = (79, 'KIGLL', CountType.SUCCESSES, Corner.RED)

    def __init__(self, id: int, abbr: str, count_type: CountType, fighter: Corner):
        self.id = id
        self.abbr = abbr
        self.count_type = count_type
        self.fighter = fighter


class GrapplingType(Enum):
    TAKEDOWNS_LANDED_BLUE    = (0, 'TDL', CountType.SUCCESSES, Corner.BLUE)
    TAKEDOWNS_LANDED_RED     = (1, 'TDL', CountType.SUCCESSES, Corner.RED)
    TAKEDOWNS_ATTEMPTED_BLUE = (2, 'TDA', CountType.TRIALS,    Corner.BLUE)
    TAKEDOWNS_ATTEMPTED_RED  = (3, 'TDA', CountType.TRIALS,    Corner.RED)

    REVERSALS_LANDED_BLUE = (4, 'RVL', CountType.SUCCESSES, Corner.BLUE)
    REVERSALS_LANDED_RED  = (5, 'RVL', CountType.SUCCESSES, Corner.RED)

    STANDUPS_LANDED_BLUE = (6, 'SUL', CountType.SUCCESSES, Corner.BLUE)
    STANDUPS_LANDED_RED  = (7, 'SUL', CountType.SUCCESSES, Corner.RED)

    SUBMISSIONS_ATTEMPTED_BLUE = (8,  'SMA', CountType.TRIALS,    Corner.BLUE)
    SUBMISSIONS_ATTEMPTED_RED  = (9,  'SMA', CountType.TRIALS,    Corner.RED)
    SUBMISSIONS_LANDED_BLUE    = (10, 'SML', CountType.SUCCESSES, Corner.BLUE)
    SUBMISSIONS_LANDED_RED     = (11, 'SML', CountType.SUCCESSES, Corner.RED)

    ADVANCES_LANDED_BLUE = (12, 'AVL', CountType.SUCCESSES, Corner.BLUE)
    ADVANCES_LANDED_RED  = (13, 'AVL', CountType.SUCCESSES, Corner.RED)

    STANDUPS_LANDED_FROM_BACK_CONTROL_BLUE       = (14, 'SUBCL',   CountType.SUCCESSES, Corner.BLUE)
    STANDUPS_LANDED_FROM_BACK_CONTROL_RED        = (15, 'SUBCL',   CountType.SUCCESSES, Corner.RED)
    STANDUPS_LANDED_FROM_GUARD_CONTROL_BLUE      = (16, 'SUGUCL',  CountType.SUCCESSES, Corner.BLUE)
    STANDUPS_LANDED_FROM_GUARD_CONTROL_RED       = (17, 'SUGUCL',  CountType.SUCCESSES, Corner.RED)
    STANDUPS_LANDED_FROM_HALF_GUARD_CONTROL_BLUE = (18, 'SUHGCL',  CountType.SUCCESSES, Corner.BLUE)
    STANDUPS_LANDED_FROM_HALF_GUARD_CONTROL_RED  = (19, 'SUHGCL',  CountType.SUCCESSES, Corner.RED)
    STANDUPS_LANDED_FROM_MISC_CONTROL_BLUE       = (20, 'SUMICL',  CountType.SUCCESSES, Corner.BLUE)
    STANDUPS_LANDED_FROM_MISC_CONTROL_RED        = (21, 'SUMICL',  CountType.SUCCESSES, Corner.RED)
    STANDUPS_LANDED_FROM_MOUNT_CONTROL_BLUE      = (22, 'SUMOCL',  CountType.SUCCESSES, Corner.BLUE)
    STANDUPS_LANDED_FROM_MOUNT_CONTROL_RED       = (23, 'SUMOCL',  CountType.SUCCESSES, Corner.RED)
    STANDUPS_LANDED_FROM_SIDE_CONTROL_BLUE       = (24, 'SUSCL',   CountType.SUCCESSES, Corner.BLUE)
    STANDUPS_LANDED_FROM_SIDE_CONTROL_RED        = (25, 'SUSCL',   CountType.SUCCESSES, Corner.RED)

    SUBMISSIONS_ATTEMPTED_FROM_BACK_CONTROL_BLUE       = (26, 'SMBCA',  CountType.TRIALS, Corner.BLUE)
    SUBMISSIONS_ATTEMPTED_FROM_BACK_CONTROL_RED        = (27, 'SMBCA',  CountType.TRIALS, Corner.RED)
    SUBMISSIONS_ATTEMPTED_FROM_GUARD_CONTROL_BLUE      = (28, 'SMGUCA', CountType.TRIALS, Corner.BLUE)
    SUBMISSIONS_ATTEMPTED_FROM_GUARD_CONTROL_RED       = (29, 'SMGUCA', CountType.TRIALS, Corner.RED)
    SUBMISSIONS_ATTEMPTED_FROM_HALF_GUARD_CONTROL_BLUE = (30, 'SMHGCA', CountType.TRIALS, Corner.BLUE)
    SUBMISSIONS_ATTEMPTED_FROM_HALF_GUARD_CONTROL_RED  = (31, 'SMHGCA', CountType.TRIALS, Corner.RED)
    SUBMISSIONS_ATTEMPTED_FROM_MISC_CONTROL_BLUE       = (32, 'SMMICA', CountType.TRIALS, Corner.BLUE)
    SUBMISSIONS_ATTEMPTED_FROM_MISC_CONTROL_RED        = (33, 'SMMICA', CountType.TRIALS, Corner.RED)
    SUBMISSIONS_ATTEMPTED_FROM_MOUNT_CONTROL_BLUE      = (34, 'SMMOCA', CountType.TRIALS, Corner.BLUE)
    SUBMISSIONS_ATTEMPTED_FROM_MOUNT_CONTROL_RED       = (35, 'SMMOCA', CountType.TRIALS, Corner.RED)
    SUBMISSIONS_ATTEMPTED_FROM_SIDE_CONTROL_BLUE       = (36, 'SMSCA',  CountType.TRIALS, Corner.BLUE)
    SUBMISSIONS_ATTEMPTED_FROM_SIDE_CONTROL_RED        = (37, 'SMSCA',  CountType.TRIALS, Corner.RED)
    SUBMISSIONS_LANDED_FROM_BACK_CONTROL_BLUE          = (38, 'SMBCL',  CountType.SUCCESSES, Corner.BLUE)
    SUBMISSIONS_LANDED_FROM_BACK_CONTROL_RED           = (39, 'SMBCL',  CountType.SUCCESSES, Corner.RED)
    SUBMISSIONS_LANDED_FROM_GUARD_CONTROL_BLUE         = (40, 'SMGUCL', CountType.SUCCESSES, Corner.BLUE)
    SUBMISSIONS_LANDED_FROM_GUARD_CONTROL_RED          = (41, 'SMGUCL', CountType.SUCCESSES, Corner.RED)
    SUBMISSIONS_LANDED_FROM_HALF_GUARD_CONTROL_BLUE    = (42, 'SMHGCL', CountType.SUCCESSES, Corner.BLUE)
    SUBMISSIONS_LANDED_FROM_HALF_GUARD_CONTROL_RED     = (43, 'SMHGCL', CountType.SUCCESSES, Corner.RED)
    SUBMISSIONS_LANDED_FROM_MISC_CONTROL_BLUE          = (44, 'SMMICL', CountType.SUCCESSES, Corner.BLUE)
    SUBMISSIONS_LANDED_FROM_MISC_CONTROL_RED           = (45, 'SMMICL', CountType.SUCCESSES, Corner.RED)
    SUBMISSIONS_LANDED_FROM_MOUNT_CONTROL_BLUE         = (46, 'SMMOCL', CountType.SUCCESSES, Corner.BLUE)
    SUBMISSIONS_LANDED_FROM_MOUNT_CONTROL_RED          = (47, 'SMMOCL', CountType.SUCCESSES, Corner.RED)
    SUBMISSIONS_LANDED_FROM_SIDE_CONTROL_BLUE          = (48, 'SMSCL',  CountType.SUCCESSES, Corner.BLUE)
    SUBMISSIONS_LANDED_FROM_SIDE_CONTROL_RED           = (49, 'SMSCL',  CountType.SUCCESSES, Corner.RED)

    TAKEDOWNS_ATTEMPTED_FROM_CLINCH_CONTROL_BLUE = (50, 'TDCCA', CountType.TRIALS,    Corner.BLUE)
    TAKEDOWNS_ATTEMPTED_FROM_CLINCH_CONTROL_RED  = (51, 'TDCCA', CountType.TRIALS,    Corner.RED)
    TAKEDOWNS_LANDED_FROM_CLINCH_CONTROL_BLUE    = (52, 'TDCCL', CountType.SUCCESSES, Corner.BLUE)
    TAKEDOWNS_LANDED_FROM_CLINCH_CONTROL_RED     = (53, 'TDCCL', CountType.SUCCESSES, Corner.RED)

    def __init__(self, id: int, abbr: str, count_type: CountType, fighter: Corner):
        self.id = id
        self.abbr = abbr
        self.count_type = count_type
        self.fighter = fighter


class ControlType(Enum):
    CONTROL_BLUE = (0, 'C', Corner.BLUE)
    CONTROL_RED  = (1, 'C', Corner.RED)

    GROUND_CONTROL_BLUE = (2, 'GC', Corner.BLUE)
    GROUND_CONTROL_RED  = (3, 'GC', Corner.RED)

    CLINCH_CONTROL_BLUE = (4, 'CC', Corner.BLUE)
    CLINCH_CONTROL_RED  = (5, 'CC', Corner.RED)

    BACK_CONTROL_BLUE       = (6,  'BC',  Corner.BLUE)
    BACK_CONTROL_RED        = (7,  'BC',  Corner.RED)
    GUARD_CONTROL_BLUE      = (8,  'GUC',  Corner.BLUE)
    GUARD_CONTROL_RED       = (9,  'GUC',  Corner.RED)
    HALF_GUARD_CONTROL_BLUE = (10, 'HGC',  Corner.BLUE)
    HALF_GUARD_CONTROL_RED  = (11, 'HGC',  Corner.RED)
    MISC_CONTROL_BLUE       = (12, 'MIC', Corner.BLUE)
    MISC_CONTROL_RED        = (13, 'MIC', Corner.RED)
    MOUNT_CONTROL_BLUE      = (14, 'MOC', Corner.BLUE)
    MOUNT_CONTROL_RED       = (15, 'MOC', Corner.RED)
    SIDE_CONTROL_BLUE       = (16, 'SC',  Corner.BLUE)
    SIDE_CONTROL_RED        = (17, 'SC',  Corner.RED)

    def __init__(self, id: int, abbr: str, fighter: Corner):
        self.id = id
        self.abbr = abbr
        self.fighter = fighter


class PositionType(Enum):
    STANDING         = (0, 'ST')
    DISTANCE         = (1, 'DT')
    CLINCH           = (2, 'CT')
    GROUND           = (3, 'GT')
    NEUTRAL          = (4, 'NT')
    NEUTRAL_STANDING = (5, 'NST')
    NEUTRAL_DISTANCE = (6, 'NDT')
    NEUTRAL_CLINCH   = (7, 'NCT')
    NEUTRAL_GROUND   = (8, 'NGT')

    def __init__(self, id: int, abbr: str):
        self.id = id
        self.abbr = abbr


StatsType: TypeAlias = (
        StrikingType
        | GrapplingType
        | ControlType
        | PositionType
)