from stats.stats_type import StrikingType
from typing import Dict, Tuple


STRIKING_HIERARCHY: Dict[StrikingType, Tuple[StrikingType, ...]] = {
    StrikingType.STRIKES_FROM_STANDING_AT_HEAD_ATTEMPTED_BLUE: (
        StrikingType.STRIKES_FROM_DISTANCE_AT_HEAD_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_HEAD_ATTEMPTED_BLUE
    ),
    StrikingType.STRIKES_FROM_STANDING_AT_BODY_ATTEMPTED_BLUE: (
        StrikingType.STRIKES_FROM_DISTANCE_AT_BODY_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_BODY_ATTEMPTED_BLUE
    ),
    StrikingType.STRIKES_FROM_STANDING_AT_LEGS_ATTEMPTED_BLUE: (
        StrikingType.STRIKES_FROM_DISTANCE_AT_LEGS_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_LEGS_ATTEMPTED_BLUE
    ),

    StrikingType.STRIKES_AT_HEAD_ATTEMPTED_BLUE: (
        StrikingType.STRIKES_FROM_DISTANCE_AT_HEAD_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_HEAD_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_GROUND_AT_HEAD_ATTEMPTED_BLUE
    ),

    StrikingType.STRIKES_AT_BODY_ATTEMPTED_BLUE: (
        StrikingType.STRIKES_FROM_DISTANCE_AT_BODY_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_BODY_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_GROUND_AT_BODY_ATTEMPTED_BLUE
    ),

    StrikingType.STRIKES_AT_LEGS_ATTEMPTED_BLUE: (
        StrikingType.STRIKES_FROM_DISTANCE_AT_LEGS_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_LEGS_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_GROUND_AT_LEGS_ATTEMPTED_BLUE
    ),

    StrikingType.STRIKES_FROM_DISTANCE_ATTEMPTED_BLUE: (
        StrikingType.STRIKES_FROM_DISTANCE_AT_HEAD_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_DISTANCE_AT_BODY_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_DISTANCE_AT_LEGS_ATTEMPTED_BLUE,
    ),

    StrikingType.STRIKES_FROM_CLINCH_ATTEMPTED_BLUE: (
        StrikingType.STRIKES_FROM_CLINCH_AT_HEAD_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_BODY_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_LEGS_ATTEMPTED_BLUE,
    ),

    StrikingType.STRIKES_FROM_GROUND_ATTEMPTED_BLUE: (
        StrikingType.STRIKES_FROM_GROUND_AT_HEAD_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_GROUND_AT_BODY_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_GROUND_AT_LEGS_ATTEMPTED_BLUE,
    ),

    StrikingType.STRIKES_FROM_STANDING_ATTEMPTED_BLUE: (
        StrikingType.STRIKES_FROM_DISTANCE_AT_HEAD_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_DISTANCE_AT_BODY_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_DISTANCE_AT_LEGS_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_HEAD_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_BODY_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_LEGS_ATTEMPTED_BLUE
    ),

    StrikingType.STRIKES_ATTEMPTED_BLUE: (
        StrikingType.STRIKES_FROM_DISTANCE_AT_HEAD_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_DISTANCE_AT_BODY_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_DISTANCE_AT_LEGS_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_HEAD_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_BODY_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_LEGS_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_GROUND_AT_HEAD_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_GROUND_AT_BODY_ATTEMPTED_BLUE,
        StrikingType.STRIKES_FROM_GROUND_AT_LEGS_ATTEMPTED_BLUE,
    ),

    StrikingType.STRIKES_FROM_STANDING_AT_HEAD_LANDED_BLUE: (
        StrikingType.STRIKES_FROM_DISTANCE_AT_HEAD_LANDED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_HEAD_LANDED_BLUE
    ),
    StrikingType.STRIKES_FROM_STANDING_AT_BODY_LANDED_BLUE: (
        StrikingType.STRIKES_FROM_DISTANCE_AT_BODY_LANDED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_BODY_LANDED_BLUE
    ),
    StrikingType.STRIKES_FROM_STANDING_AT_LEGS_LANDED_BLUE: (
        StrikingType.STRIKES_FROM_DISTANCE_AT_LEGS_LANDED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_LEGS_LANDED_BLUE
    ),

    StrikingType.STRIKES_AT_HEAD_LANDED_BLUE: (
        StrikingType.STRIKES_FROM_DISTANCE_AT_HEAD_LANDED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_HEAD_LANDED_BLUE,
        StrikingType.STRIKES_FROM_GROUND_AT_HEAD_LANDED_BLUE
    ),

    StrikingType.STRIKES_AT_BODY_LANDED_BLUE: (
        StrikingType.STRIKES_FROM_DISTANCE_AT_BODY_LANDED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_BODY_LANDED_BLUE,
        StrikingType.STRIKES_FROM_GROUND_AT_BODY_LANDED_BLUE
    ),

    StrikingType.STRIKES_AT_LEGS_LANDED_BLUE: (
        StrikingType.STRIKES_FROM_DISTANCE_AT_LEGS_LANDED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_LEGS_LANDED_BLUE,
        StrikingType.STRIKES_FROM_GROUND_AT_LEGS_LANDED_BLUE
    ),

    StrikingType.STRIKES_FROM_DISTANCE_LANDED_BLUE: (
        StrikingType.STRIKES_FROM_DISTANCE_AT_HEAD_LANDED_BLUE,
        StrikingType.STRIKES_FROM_DISTANCE_AT_BODY_LANDED_BLUE,
        StrikingType.STRIKES_FROM_DISTANCE_AT_LEGS_LANDED_BLUE,
    ),

    StrikingType.STRIKES_FROM_CLINCH_LANDED_BLUE: (
        StrikingType.STRIKES_FROM_CLINCH_AT_HEAD_LANDED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_BODY_LANDED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_LEGS_LANDED_BLUE,
    ),

    StrikingType.STRIKES_FROM_GROUND_LANDED_BLUE: (
        StrikingType.STRIKES_FROM_GROUND_AT_HEAD_LANDED_BLUE,
        StrikingType.STRIKES_FROM_GROUND_AT_BODY_LANDED_BLUE,
        StrikingType.STRIKES_FROM_GROUND_AT_LEGS_LANDED_BLUE,
    ),

    StrikingType.STRIKES_FROM_STANDING_LANDED_BLUE: (
        StrikingType.STRIKES_FROM_DISTANCE_AT_HEAD_LANDED_BLUE,
        StrikingType.STRIKES_FROM_DISTANCE_AT_BODY_LANDED_BLUE,
        StrikingType.STRIKES_FROM_DISTANCE_AT_LEGS_LANDED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_HEAD_LANDED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_BODY_LANDED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_LEGS_LANDED_BLUE
    ),

    StrikingType.STRIKES_LANDED_BLUE: (
        StrikingType.STRIKES_FROM_DISTANCE_AT_HEAD_LANDED_BLUE,
        StrikingType.STRIKES_FROM_DISTANCE_AT_BODY_LANDED_BLUE,
        StrikingType.STRIKES_FROM_DISTANCE_AT_LEGS_LANDED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_HEAD_LANDED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_BODY_LANDED_BLUE,
        StrikingType.STRIKES_FROM_CLINCH_AT_LEGS_LANDED_BLUE,
        StrikingType.STRIKES_FROM_GROUND_AT_HEAD_LANDED_BLUE,
        StrikingType.STRIKES_FROM_GROUND_AT_BODY_LANDED_BLUE,
        StrikingType.STRIKES_FROM_GROUND_AT_LEGS_LANDED_BLUE,
    )
}